[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

# Wichtig für micro-ROS
board_microros_transport = serial 

lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino.git#humble
    # Hier kommen später deine Treiber für den VNH2SP30 rein